export const LOAD_ACCOUNT = 'containers/VTXDashboard/LOAD_ACCOUNT'
export const LOAD_ACCOUNT_SUCCESS = 'containers/VTXDashboard/LOAD_ACCOUNT_SUCCESS'
export const LOAD_TOKEN_BALANCE = 'containers/VTXDashboard/LOAD_TOKEN_BALANCE'
export const LOAD_TOKEN_BALANCE_SUCCESS = 'containers/VTXDashboard/LOAD_TOKEN_BALANCE_SUCCESS'
export const LOAD_CONTRACT_ERROR = 'containers/VTXDashboard/LOAD_CONTRACT_ERROR'
export const LOAD_VTX_DATA = 'containers/VTXDashboard/LOAD_VTX_DATA'
export const TRANSFER = 'containers/VTXDashboard/TRANSFER'
export const TRANSFER_SUCCESS = 'containers/VTXDashboard/TRANSFER_SUCCESS'
